---
title:enum
---
flowchart LR
	21@{ shape: stadium,label: "UnitVariant" }
	10@{ shape: odd,label: "(& 'b T , i32)" }
	1@{ shape: hexagon,label: "EnumSample" }
	3@{ shape: lean-l,label: "< 'a , 'b , T >" }
	9@{ shape: subroutine,label: "#35; [doc = \"document\"]" }
	13@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_b\")]" }
	16@{ shape: odd,label: "reference" }
	19@{ shape: odd,label: "tuple" }
	22@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_d\")]" }
	5@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_a\")]" }
	6@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_a\")]" }
	4@{ shape: lean-l,label: "where 'a : 'b ," }
	7@{ shape: stadium,label: "TupleVariant" }
	8@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_b\")]" }
	15@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_c\")]" }
	17@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_c\")]" }
	20@{ shape: subroutine,label: "#35; [doc = \"foo\"]" }
	2@{ shape: lean-l,label: "< 'a , 'b , T : 'b >" }
	12@{ shape: odd,label: "& 'a str" }
	14@{ shape: stadium,label: "NamedVariant" }
	18@{ shape: odd,label: "value" }
	11@{ shape: subroutine,label: "#35; [cfg (feature = \"dummy_b\")]" }
	1 -- "impl" --> 2
	1 -- "type" --> 3
	1 -- "where" --> 4
	1 -- "attr" --> 5
	1 -- "attr" --> 6
	1 -- "variant" --> 7
	1 -- "variant" --> 14
	1 -- "variant" --> 21
	7 -- "attr" --> 8
	7 -- "attr" --> 9
	7 -- "field" --> 10
	7 -- "field" --> 12
	10 -- "attr" --> 11
	12 -- "attr" --> 13
	14 -- "attr" --> 15
	14 -- "field" --> 16
	14 -- "field" --> 18
	14 -- "field" --> 19
	16 -- "attr" --> 17
	19 -- "attr" --> 20
	21 -- "attr" --> 22
