[package]
name = "playground"
version = "0.1.0"
edition = "2024"

[dependencies]
proc_macro = { path = "../proc_macro" }
syn = { version = "*", features = ["full", "visit"] }
quote = "*"
proc-macro2 = "*"
regex = "*"
mermaid_writer = { path = "../mermaid_writer" }
clap = { version = "4.5.58", features = ["derive"] }
rand = "*"


[features]
dummy_a = []
dummy_b = []
dummy_c = []
dummy_d = []

